baseurl = "https://blog.olivia-data.com/"
relativeurls = false
languageCode = "en-us"
title = "Olivia data"
theme = "hugo-lithium-theme"
googleAnalytics = "UA-94088010-1"
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "_files$", "_cache$"]

canonifyURLs = true

PygmentsCodeFences = true
PygmentsStyle = "tango"

[permalinks]
    post = "/:year/:month/:day/:slug/"

[[menu.main]]
    name = "About"
    url = "/about/"
[[menu.main]]
    name = "GitHub"
    url = "https://github.com/nibrivia/"
[[menu.main]]
    name = "Twitter"
    url = "https://twitter.com/nibrivia/"

[params]
    description = "Olivia's projects and data musings"

    [params.logo]
    url = "logo.svg"
    width = 50
    height = 50
    alt = "Logo"

